name: build
on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: bash ./gradlew assembleDebug
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: id.co.npad93.pm.t6-H071191011.apk
        path: app/build/outputs/apk/debug/app-debug.apk
